#!/usr/bin/env bash
#
# install.sh — interactive setup for backup-media.sh.
# Clone repo to server, run this. Prompts for S3 details,
# auto-scans /data/coolify for media folders, writes backup-media.conf,
# sets perms, optional cron install.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$SCRIPT_DIR/backup-media.conf"
RUNNER="$SCRIPT_DIR/backup-media.sh"
SCAN_ROOT="/data/coolify"

# Folder names that usually hold media/user uploads.
MEDIA_RE='media|uploads?|storage|public|images?|assets|files|attachments|documents'

c_bold=$'\e[1m'; c_dim=$'\e[2m'; c_grn=$'\e[32m'; c_ylw=$'\e[33m'; c_rst=$'\e[0m'
say()  { printf '%s\n' "$*"; }
hdr()  { printf '\n%s%s%s\n' "$c_bold" "$*" "$c_rst"; }
ask()  { # ask "Prompt" "default" -> echoes answer
  local p="$1" def="${2:-}" ans
  if [ -n "$def" ]; then read -rp "$p [$def]: " ans; echo "${ans:-$def}";
  else read -rp "$p: " ans; echo "$ans"; fi
}
asksecret() { local p="$1" ans; read -rsp "$p: " ans; echo >&2; echo "$ans"; }

# ---------- 1. rclone ----------
hdr "1/5  rclone"
if command -v rclone >/dev/null 2>&1; then
  say "${c_grn}found${c_rst} $(rclone version | head -1)"
else
  say "${c_ylw}rclone not installed.${c_rst}"
  if [ "$(ask 'Install now? (y/n)' y)" = "y" ]; then
    curl https://rclone.org/install.sh | sudo bash
  else
    say "Install rclone then re-run."; exit 1
  fi
fi

# ---------- 2. S3 details ----------
hdr "2/5  Hetzner S3 details"
BUCKET="$(ask 'Bucket name' instancebackup)"
SERVER_NAME="$(ask 'Server name (folder under bucket)' "$(hostname -s)")"
REGION="$(ask 'Region' nbg1)"
ENDPOINT="$(ask 'Endpoint' "https://${REGION}.your-objectstorage.com")"
ACCESS_KEY="$(ask 'S3 access key')"
SECRET_KEY="$(asksecret 'S3 secret key')"
MODE="$(ask 'Mode: sync (mirror) or copy (additive)' sync)"
if [ "$(ask 'Keep overwritten/deleted versions in an archive? (y/n)' y)" = "y" ]; then
  KEEP_OLD="$(ask 'Archive folder name' .archive)"
  ARCHIVE_KEEP_DAYS="$(ask 'Delete archived files older than N days (empty = keep forever)' 30)"
else
  KEEP_OLD=""; ARCHIVE_KEEP_DAYS=""
fi

# ---------- 3. scan settings + preview ----------
hdr "3/5  Auto-discovery"
say "Backup scans ${c_bold}$SCAN_ROOT${c_rst} for media folders on EVERY run."
say "New Coolify apps are picked up automatically — no reconfigure needed."
SCAN_ROOT="$(ask 'Scan root' "$SCAN_ROOT")"
MEDIA_NAMES="$(ask 'Folder names (regex)' "$MEDIA_RE")"

say "\n${c_dim}Folders matching right now:${c_rst}"
if [ -d "$SCAN_ROOT" ]; then
  found=0
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    found=$((found+1))
    printf '  %s%s%s  ->  %s\n' "$c_grn" "$d" "$c_rst" "${SERVER_NAME}/${d#"$SCAN_ROOT"/}"
  done < <(find "$SCAN_ROOT" -type d -regextype posix-extended \
             -iregex ".*/(${MEDIA_NAMES})" 2>/dev/null | sort -u)
  [ "$found" -eq 0 ] && say "  ${c_ylw}(none yet — they'll be caught once apps create them)${c_rst}"
else
  say "  ${c_ylw}$SCAN_ROOT not found on this host.${c_rst}"
fi

# ---------- 4. write conf ----------
hdr "4/5  Write $CONF"
{
  echo "# backup-media.conf — generated by install.sh on $(date)"
  echo "# chmod 600 — holds secrets."
  echo
  echo "BUCKET=\"$BUCKET\""
  echo "SERVER_NAME=\"$SERVER_NAME\""
  echo "AWS_ACCESS_KEY_ID=\"$ACCESS_KEY\""
  echo "AWS_SECRET_ACCESS_KEY=\"$SECRET_KEY\""
  echo
  echo "PROVIDER=\"Other\""
  echo "REGION=\"$REGION\""
  echo "ENDPOINT=\"$ENDPOINT\""
  echo
  echo "MODE=\"$MODE\""
  echo "KEEP_OLD=\"$KEEP_OLD\""
  echo "ARCHIVE_KEEP_DAYS=\"$ARCHIVE_KEEP_DAYS\""
  echo
  echo "BWLIMIT=\"0\""
  echo "TRANSFERS=\"8\""
  echo "LOG=\"/var/log/backup-media.log\""
  echo
  echo "SCAN_ROOT=\"$SCAN_ROOT\""
  echo "MEDIA_NAMES=\"$MEDIA_NAMES\""
  echo "EXTRA_PATHS=()"
} > "$CONF"

chmod 600 "$CONF"
chmod 700 "$RUNNER" 2>/dev/null || true
say "${c_grn}wrote${c_rst} $CONF (chmod 600)"

# ---------- 5. test + cron ----------
hdr "5/5  Test & schedule"
if [ "$(ask 'Run a full dry-run now? (y/n)' y)" = "y" ]; then
  say "${c_dim}dry-run: scans + shows what each path would transfer, changes nothing${c_rst}"
  RCLONE_DRY=1 "$RUNNER" "$CONF" || true
  say "${c_dim}(dry-run uses the real runner; see /var/log/backup-media.log)${c_rst}"
fi

if [ "$(ask 'Install cron job? (y/n)' y)" = "y" ]; then
  sched="$(ask 'Cron schedule' '0 2 * * *')"
  line="$sched $RUNNER"
  ( crontab -l 2>/dev/null | grep -vF "$RUNNER"; echo "$line" ) | crontab -
  say "${c_grn}cron installed:${c_rst} $line"
fi

hdr "Done."
say "Edit config any time:   $CONF"
say "Run manually:           $RUNNER"
say "Logs:                   /var/log/backup-media.log"
